# Conversion
markdown:    kramdown

# Permalinks
permalink:   pretty
future:      false
baseurl:     ''
url:         https://tiagoamaro.com.br

# Setup
exclude:     ['Gemfile', 'LICENSE', 'README', 'CNAME']

# Jekyll SEO tag
title: "Tiago Padrela Amaro"

# Plugins
plugins:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

gist:
  noscript: false

sass:
  sass_dir: _scss
  style: compressed
