# Conversion
markdown:    kramdown

# Permalinks
permalink:   pretty
future:      false
baseurl:     ''
url:         https://www.tiagoamaro.com.br

# Setup
exclude:     ['Gemfile', 'LICENSE', 'README', 'CNAME']

# Plugins
plugins:
  - jekyll-gist
  - jekyll-sitemap

gist:
  noscript: false

sass:
  sass_dir: _scss
  style: compressed
