# Conversion
markdown:    redcarpet

# Permalinks
permalink:   pretty
future:      false
baseurl:     ''
url:         https://tiagoamaro.com.br

# Setup
exclude:     ['Gemfile', 'LICENSE', 'README', 'CNAME']
paginate:    5

# Plugins
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

gist:
  noscript: false
