# Conversion
markdown:    redcarpet

# Permalinks
permalink:   pretty
future:      false
baseurl:     /

# Setup
exclude:     ['Gemfile', 'LICENSE', 'README', 'CNAME']
paginate:    5

# Plugins
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
